#!/usr/bin/env bash

set -e

main()
{
    case $1 in
        shell)
            bash
            ;;
        develop)
            printf "\t ..: Starting the developer loop\n"
            find ./ -name "*.py" | entr -r ./penny-scan.py --budget 250 --go-live --pair ETHEUR
            ;;
        *)
            printf "\t ..: Invoking '$*'\n"
            exec "$@"
            ;;
    esac
}

cd /app/src
main "$@"
